### ISSUE TITLE
Repository needs a shorter title (?)

### ISSUE THREAD

**Issue by zlatanvasovic** [sjparsons/example-react-app-with-create-react-app#1]
It may look fine on first sight to have a long repository title, but it's really bad for reachability of the repository. Please consider using a shorter title, that'll surely help your project reach more attention and grow (if that's needed).

**example-react-app** is good enough for the repository title, in my opinion.

**Comment by sjparsons** [comment]
Good point... was just trying to be clear what it was about.

**Comment by zlatanvasovic** [comment]
@sjparsons Still, it's your repository, not React's so you can name it whatever you want. Also, some of the best projects have totally crazy, but short names, so don't worry about being clear in repository title.
